config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users, :only => [:show]
  
    resources :clubs do
      resources :announcements
      resources :members, :controller => "memberships" do
        post "make_admin"
        post "del_admin"
      end
      resources :books do
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
    
    root "home#index"

    get '*unmatched_route', to: 'errors#not_found'
end

app/models/membership.rb
class Membership < ActiveRecord::Base
    belongs_to :club
    belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
    def new
        @club = Club.find(params[:club_id])
        
        if params[:email].present? and params[:email].length > 5 and params[:email].include?("@")
            @users = User.where("email LIKE ?" , "%#{params[:email].downcase}%")
        end
    end
    
    def create
        @user = User.find(params[:user_id])
        @club = Club.find(params[:club_id])
        
        @membership = @user.memberships.build(:club_id => @club.id) unless @user.memberships.find_by_club_id(@club.id)

        if @membership and @membership.save
            flash[:success] = "You have added #{@user.username} to the club."
            redirect_to edit_club_path(:id => @club.id)
            else
            if @user.memberships.find_by_club_id(@club.id)
                flash[:danger] = "This user is already a member."
                redirect_to :back
            else
              flash[:danger] = "Unable to add member."
              redirect_to :back
            end
        end
    end
    
    def show
        @club = Club.find(params[:club_id])
        @membership = @club.memberships.find(params[:id])
    end
    
    def make_admin
        @club = Club.find(params[:club_id])
        @membership = @club.memberships.find(params[:member_id])
        if @club.memberships.find_by_user_id(current_user.id).admin == true
            if @membership.admin == false
                @membership.admin = true
                @membership.save
                flash[:success] = "Member has been made admin."
            else
                flash[:success] = "This member is already an admin."
            end
        else
            flash[:danger] = "You do not have permission."
        end
        redirect_to :back
    end
    
    def del_admin
        @club = Club.find(params[:club_id])
        @membership = @club.memberships.find(params[:member_id])
        if @club.memberships.find_by_user_id(current_user.id).admin == true
            if @membership.admin
                @membership.admin = false
                @membership.save
                flash[:success] = "Member has been stripped of admin rights."
            else
                flash[:success] = "This member cannot be stripped of admin rights."
            end
        else
            flash[:danger] = "You do not have permission."
        end
        redirect_to :back
    end
    
    def destroy
        @club = Club.find(params[:club_id])
        @membership = @club.memberships.find(params[:membership_id])
        if @membership.user == current_user
            @membership.destroy
            if @club.memberships.count == 0 
                @club.destroy
                flash[:danger] = "The club has been disbanded."
            end
            flash[:danger] = "You have left the club."
            redirect_to root_path
        else
            @membership.destroy
            flash[:success] = "Member has been kicked."
            redirect_to :back
        end
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/new.html.erb
<% @title = "Add Member" %>
<div class="container">
    <div class="row">
        <h1 class="text-center">Adding members for <%= @club.name %></h1>
        <div class="col-md-offset-4 col-md-4 col-md-offset-4">
            <br>
            <%= form_tag(new_club_member_path, method: :get) do %>
                <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Search by email" %>
                <%= submit_tag "Search", class: "btn btn-primary btn-md", style: "margin-top: 10px; display: none" %>
            <% end %>
        </div>
    </div>
    <br><br>
    <% if @users %>
        <% @users.each do |user| %>
            <ul class="list-group">
                <li class="list-group-item">
                    <%= link_to( "Add this member", club_members_path(:action => "create", :user_id => user.id), :method => :post) %>
                    <br>
                    Username: <%= user.username %>
                    <br>
                    First name: <%= user.first_name %>
                </li>
            </ul>
        <% end %>
    <% end %>
</div>