config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users, :only => [:show]
  
    resources :clubs do
      resources :announcements
      resources :members, :controller => "memberships" do
        post "make_admin"
        post "del_admin"
      end
      resources :books do
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
    
    root "home#index"

    get '*unmatched_route', to: 'errors#not_found'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
    belongs_to :club
    belongs_to :user
    
    validates :subject, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 3 }
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :readings
    has_many :clubs, through: :readings
end

app/models/club.rb
class Club < ActiveRecord::Base
    belongs_to :user
    has_many :readings
    has_many :announcements
    has_many :books, through: :readings
    has_many :memberships
    validates_length_of :memberships, maximum: 20
    has_many :users, through: :memberships

    validates :name, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :discussion
    belongs_to :user
    
    validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
    belongs_to :reading
    belongs_to :user
    has_many :comments
    
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true, length: { minimum: 5 }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
    belongs_to :club
    belongs_to :user
end

app/models/reading.rb
class Reading < ActiveRecord::Base
    belongs_to :club
    belongs_to :book
    has_many :discussions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :discussions
  has_many :comments
  has_many :announcements
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!

    def index
    end
    
    def new
        @club = Club.find(params[:club_id])
        if params[:search].present? and params[:search].length > 3
            @books = GoogleBooks.search("#{params[:search].downcase}", {:order_by => 'relevance'})
        end
        @book = @club.books.build
    end
    
    def create
        @club = Club.find(params[:club_id])
        
        isbn = params[:isbn]
        chosen = GoogleBooks.search(isbn).first
    
        @book = Book.new
        @book.title = chosen.title
        @book.description = chosen.description
        @book.author = chosen.authors
        @book.isbn = chosen.isbn
        @book.image = chosen.image_link(:zoom => 6)
        @book.save
        
        @club.books << @book
        
        if @book.save
            make_prev = @club.readings.where(current: true).first
            if make_prev then
                make_prev.current = false
                make_prev.save
            end
            
            set_current = @club.readings.find_by_book_id(@book.id)
            set_current.current = true
            set_current.save
            redirect_to club_book_path(:id => @book.id)
            flash[:success] = "This book has been made the club's new reading."
        else
            render 'new'
        end
    end
    
    def show
        @book = Book.find(params[:id])
        @club = Club.find(params[:club_id])
        @reading = @club.readings.where(:book_id => @book.id).first
        
        @discussion = Discussion.new
        @comment = Comment.new
    end
    
    private
    def book_params
        params.require(:book).permit(:title, :description, :author, :isbn, :search)
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :authenticate_user!

    def index
        @club = Club.all
    end
    
    def new
        @club = current_user.clubs.build
    end
    
    def create
        @club = current_user.clubs.build(club_params)
        
        if @club.save
            current_user.clubs << @club
            ad = @club.memberships.find_by_user_id(current_user.id)
            ad.admin = true
            ad.save!
            redirect_to @club
        else
            if @club.errors.any?
                @club.errors.full_messages.each do |msg|
                  flash[:danger] = msg
              end
             end
            redirect_to new_club_path
        end
    end
    
    def show
        @club = Club.find(params[:id])
    end
    
    def edit
        @club = Club.find(params[:id])
        ad = @club.memberships.find_by_user_id(current_user.id)
        if ad.admin = true then
            render 'edit'
        else
            flash[:danger] = "You are not an admin of this club."
            redirect_to @club
        end
    end
    
    private
    def club_params
        params.require(:club).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if current_user and current_user.clubs.count >= 1
            @user_clubs = current_user.clubs
            @active_club = @user_clubs.order('updated_at DESC').first
            if @active_club.readings.count >= 1
                @current_reading = @active_club.readings.where(:current => true)[0]
                @current_book = @current_reading.book
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% @title = "Book Club" %>
<div class="jumbotron">
    <% if current_user %>
        <h1 class="display-3">Hello, <%=current_user.username %></h1>
        <p class="lead">Let's get reading!</p>
        <hr class="my-4">
        <p>Why not catch up on some books or maybe start a club of your own?</p>
        <%= link_to "My Clubs", clubs_path, class: "btn btn-info btn-lg"%>
        <%= link_to "New Club", new_club_path, class: "btn btn-info btn-lg hdr-button" %>
    <% else %>
    <h1 class="display-3">Welcome</h1>
        <p class="lead">Book Club is an online community for reading and discussing books with friends.</p>
        <hr class="my-4">
        <p>Let's get reading!  <%= link_to "Sign Up!", "/users/sign_up", class: "btn btn-info btn-md hdr-button"%></p>
        <p>Already a member?<%= link_to "Log In!", "/users/sign_in", class: "btn btn-info btn-md hdr-button" %></p>
    <% end %>
</div>


<div class="text-center container" style="padding-bottom: 150px">
    <% if @active_club %>
        <h2>Recently Active Club:</h2>
        <div class="col-lg-4 col-md-4 col-sm-3"><!--SPACE FILLER--></div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 home-page-club">
                <h3><%= link_to @active_club, style: "text-decoration: none; color: #333333" do %></h3>
                    <h3><%= @active_club.name %></h3>
                    <% if @active_club.readings.count >= 1 %>
                        <p class="text-muted">Currently reading:</p>
                        <p class="text-muted"><%= @current_book.title + " by " + @current_book.author %>.</p>
                        <p class="text-muted"><%= pluralize(@current_reading.discussions.count, "discussion") %></p>
                    <% end %>
                <% end %>
            </div>
        <div class="col-lg-4 col-md-4 col-sm-3"><!--SPACE FILLER--></div>
    <% end %>
</div>