config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users, :only => [:show]
  
    resources :clubs do
      resources :announcements
      resources :members, :controller => "memberships" do
        post "make_admin"
        post "del_admin"
      end
      resources :books do
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
    
    root "home#index"

    get '*unmatched_route', to: 'errors#not_found'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
    belongs_to :club
    belongs_to :user
    
    validates :subject, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 3 }
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :readings
    has_many :clubs, through: :readings
end

app/models/club.rb
class Club < ActiveRecord::Base
    belongs_to :user
    has_many :readings
    has_many :announcements
    has_many :books, through: :readings
    has_many :memberships
    validates_length_of :memberships, maximum: 20
    has_many :users, through: :memberships

    validates :name, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :discussion
    belongs_to :user
    
    validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
    belongs_to :reading
    belongs_to :user
    has_many :comments
    
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true, length: { minimum: 5 }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
    belongs_to :club
    belongs_to :user
end

app/models/reading.rb
class Reading < ActiveRecord::Base
    belongs_to :club
    belongs_to :book
    has_many :discussions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :discussions
  has_many :comments
  has_many :announcements
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!

    def index
    end
    
    def new
        @club = Club.find(params[:club_id])
        if params[:search].present? and params[:search].length > 3
            @books = GoogleBooks.search("#{params[:search].downcase}", {:order_by => 'relevance'})
        end
        @book = @club.books.build
    end
    
    def create
        @club = Club.find(params[:club_id])
        
        isbn = params[:isbn]
        chosen = GoogleBooks.search(isbn).first
    
        @book = Book.new
        @book.title = chosen.title
        @book.description = chosen.description
        @book.author = chosen.authors
        @book.isbn = chosen.isbn
        @book.image = chosen.image_link(:zoom => 6)
        @book.save
        
        @club.books << @book
        
        if @book.save
            make_prev = @club.readings.where(current: true).first
            if make_prev then
                make_prev.current = false
                make_prev.save
            end
            
            set_current = @club.readings.find_by_book_id(@book.id)
            set_current.current = true
            set_current.save
            redirect_to club_book_path(:id => @book.id)
            flash[:success] = "This book has been made the club's new reading."
        else
            render 'new'
        end
    end
    
    def show
        @book = Book.find(params[:id])
        @club = Club.find(params[:club_id])
        @reading = @club.readings.where(:book_id => @book.id).first
        
        @discussion = Discussion.new
        @comment = Comment.new
    end
    
    private
    def book_params
        params.require(:book).permit(:title, :description, :author, :isbn, :search)
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :authenticate_user!

    def index
        @club = Club.all
    end
    
    def new
        @club = current_user.clubs.build
    end
    
    def create
        @club = current_user.clubs.build(club_params)
        
        if @club.save
            current_user.clubs << @club
            ad = @club.memberships.find_by_user_id(current_user.id)
            ad.admin = true
            ad.save!
            redirect_to @club
        else
            if @club.errors.any?
                @club.errors.full_messages.each do |msg|
                  flash[:danger] = msg
              end
             end
            redirect_to new_club_path
        end
    end
    
    def show
        @club = Club.find(params[:id])
    end
    
    def edit
        @club = Club.find(params[:id])
        ad = @club.memberships.find_by_user_id(current_user.id)
        if ad.admin = true then
            render 'edit'
        else
            flash[:danger] = "You are not an admin of this club."
            redirect_to @club
        end
    end
    
    private
    def club_params
        params.require(:club).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if current_user and current_user.clubs.count >= 1
            @user_clubs = current_user.clubs
            @active_club = @user_clubs.order('updated_at DESC').first
            if @active_club.readings.count >= 1
                @current_reading = @active_club.readings.where(:current => true)[0]
                @current_book = @current_reading.book
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/new.html.erb
<% @title = "Add Book" %>
<div class="container text-center">
    <div class="container">
        <div class="row">
            <h1>Choose a new reading for <%= @club.name %></h1>
            <div class="col-md-offset-4 col-md-4 col-md-offset-4">
                <br>
                <%= form_tag(new_club_book_path, method: :get) do %>
                    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search by Title or Author" %>
                    <%= submit_tag "Search", class: "btn btn-primary btn-md", style: "margin-top: 5px" %>
                <% end %>
            </div>
        </div>
        
        <br><br>
        <% if @books %>
            <% @books.each do |book| %>
                <ul class="list-group">
                    <li class="list-group-item">
                        <%= link_to( "Choose this book", club_books_path(:action => "create", :isbn => book.isbn), :method => :post) %>
                        <img src=<%= book.image_link(:zoom => 1) %> class="img-responsive center-block">
                        <strong><%= book.title %></strong> <br>
                        By: <%= book.authors %> <br>
                        Pages: <%= book.page_count%>
                    </li>
                </ul>
            <% end %>
        <% end %>
    </div>
</div>

app/views/books/show.html.erb
<% @title = @book.title %>
<% admin = @club.memberships.find_by_user_id(current_user.id).admin %>
<div class="container">
    <div class="row">
        <p class="text-left"><%= link_to " < Back to " + @club.name + " homepage", @club %></p>
        <div class="text-center col-lg-6 col-md-6 col-sm-6">
            <h5><em><%= @book.title %></em></h5>
            <p>By: <%= @book.author %></p>
            <p>Discussion started: <%= @book.created_at.strftime("%b %d") %></p>
            <img src=<%=@book.image %> class="img-responsive center-block book-cover">
            <a target="_blank" href="https://books.google.com/books?isbn=<%= @book.isbn %>">Read book for free here.</a>
            <% if @book.description? %>
                <h3>Description:</h3>
                <p class="text-muted">
                    <%= @book.description %>
                </p>
            <% end %>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <% if admin == true then %>
                <% if @reading.current? %>
                    <%= form_for [@club, @book, @discussion] do |f| %>
                        <h3>Add Discussion</h3>
                        <%= f.text_area :title, class: "form-control", rows: "1", placeholder: "Title" %>
                   
                        <br>
                        <%= f.text_area :body, class: "form-control", rows: "8", placeholder: "Write a discussion.." %>
                        
                        <%= f.submit "Create Discussion", class: "btn btn-primary btn-md", style: "margin-top: 5px" %>
                    <% end %>
                    <% else %>
                    <br><br><br>
                    <h4 style="color: red">Discussions are no longer being created for this book.</h4>
                <% end %>
            <% end %>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-left">Discussions</h2>
            <% if @reading.discussions.none? %>
            <p class="lead">There are no discussions yet.</p>
            <% end %>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                    <% @reading.discussions.each do |d|%>
                        <div class="panel-heading" role="tab" id="headingOne">
                          <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%=d.id%>" aria-expanded="true" aria-controls="collapseOne">
                              <%= d.title %>
                            </a>
                          </h4>
                        </div>
                        <div id="collapse_<%=d.id%>" class="panel-collapse collapse" role="tabpanel">
                          <div class="panel-body">
                            <% if d.user == current_user %>
                                <p class="small text-muted">Written by you.
                                    <small><%= link_to "Delete", club_book_discussion_destroy_path(@club, @book, :discussion_id => d.id), :method => :delete %></small>
                                </p>
                            <% else %>
                                <p class="small text-muted">Written by <%= d.user.username %></p>
                            <% end %>
                            <%= d. body %>
                            <br>
                            
                            <hr>
                            
                            <!-- COMMENTS SECTION -->
                            <p class="text-muted"><a id="comments-link" data-toggle="collapse" href="#collapse-comment-form_<%=d.id%>" aria-expanded="false" aria-controls="collapseExample">
                                <%= pluralize(d.comments.count, "comment") %>
                            </a></p>
                            
                            <a class="btn btn-md btn-default" id="comments-button" role="button" data-toggle="collapse" href="#collapse-comment-form_<%=d.id%>" aria-expanded="false" aria-controls="collapseExample">
                                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment
                            </a>
                            
                            <div class="collapse" id="collapse-comment-form_<%=d.id%>">
                              <div class="well">
                                  
                                <%=form_for [@club, @book, Discussion.find(d.id), @comment] do |f| %>
                                    <%= f.text_area :body, class: "form-control", rows: "3", placeholder: "Write something..." %>
                                    <%= f.submit :Post, class: "btn btn-md btn-primary", style: "margin-top: 3px" %>
                                <% end %>
                                
                                <br>
                                <% if d.comments.any? %>
                                    <% d.comments.each do |comment| %>
                                        <div class="panel panel-default">
                                            <div class="panel panel-body">
                                                <small>
                                                    <% if comment.user == current_user or admin == true %>
                                                    <%= link_to "Delete", club_book_discussion_comment_destroy_path(@club, @book, :discussion_id => d.id, :comment_id => comment.id), :method => :delete %>
                                                    <% end %>
                                                </small>
                                                <p class="text-muted small">
                                                    <%= time_ago_in_words(comment.created_at) %> ago <br>
                                                    <%= comment.user.username %> says:
                                                </p>
                                                <%= comment.body %>
                                            </div>
                                        </div>
                                    <% end %>
                                <% end %>
                              </div>
                            </div>
                        </div>
                     </div>
                <% end %>
        </div>
    </div>
    <br><br><br><br><br><br><br><br>
</div>

app/views/clubs/edit.html.erb
<% @title = @club.name + " Settings" %>
<div class="container">
    <div id="club_admin">
        <% if @club.memberships.find_by_user_id(current_user.id).admin == false %>
        
            <p>You are not an admin of this book club.</p>
            <%= link_to "Go back to club page", @club %>
            
            <% else %>
            
            <h1>Admin control page</h1>
            <%= link_to "Back to club page", @club %>
            <br><br>
            <p>This is where you can start new books and edit club settings and members.</p>
            <br><br>
            
            <%= button_to "Add book", new_club_book_path(:club_id => @club.id), :method => :get, class: "btn btn-primary" %>
            <br>
            <%= button_to "Make announcement", new_club_announcement_path(:club_id => @club.id), :method => :get, class: "btn btn-info" %>
            
            <br><br> 
            
            <h3><%= pluralize(@club.users.count, "member") %><p class="text-muted">(20 max)</p></h3>
            <%= button_to "Add member", new_club_member_path(:club_id => @club.id), :method => :get, class: "btn btn-primary" %>
            <div class="row">
                <% @club.users.each do |user| %>
                    <div class="col-lg-2 col-md-2 col-sm-3">
                        <div class="text-left">
                                <% membership = @club.memberships.where(:user_id => user.id).first %>
                                <% if membership.admin %>
                                    <strong>Admin</strong>
                                <% else %>
                                    <br> <!--for formatting consistency-->
                                <% end %>
                                <% if user == current_user %>
                                    <p style="margin-bottom: -2px"><strong>Me</strong> (<%= current_user.username %>)</p>
                                <% else %>
                                    <p style="margin-bottom: -2px"><%= user.username %></p>
                                <% end %>
                                <p class="text-muted">Member since <%= time_ago_in_words(membership.created_at) %> ago.</p>
                                
                                <% if user == current_user %>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#leaveClub">
                                    Leave
                                 </button>
                                  <div class="modal fade" id="leaveClub" tabindex="-1" role="dialog" aria-labelledby="leaveClub" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" id="leaveClub"Leave Club</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                            <h2>Are you sure you want to leave the club?</h2>
                                            <% if @club.memberships.count == 1 %>
                                            <br>
                                                <p>You are the last member of this club. Leaving will disban the club.</p>
                                            <% end %>
                                          <br>
                                        </div>
                                        <div class="modal-footer">
                                          <p>
                                            <button type="button" class="btn btn-success" data-dismiss="modal">Stay!</button>
                                            <%= button_to "Leave the club", club_member_path(:club_id => @club.id, :membership_id => membership.id), :method => :delete, class:"btn btn-danger" %>
                                          </p>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                <% else %>
                                    <%= link_to "Kick", club_member_path(:club_id => @club.id, :membership_id => membership.id), :method => :delete, class: "btn btn-danger btn-sm" %>
                                    
                                    <% if membership.admin %>
                                         <%= link_to "De-Admin", club_member_del_admin_path(:club_id => @club.id, :member_id => membership.id), :method => :post, class: "btn btn-danger btn-sm" %>
                                    <% else %>
                                        <%= link_to "Make Admin", club_member_make_admin_path(:club_id => @club.id, :member_id => membership.id), :method => :post, class: "btn btn-info btn-sm" %>
                                    <% end %>
                                <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/clubs/index.html.erb
<% @title = "My Clubs" %>
<div class="container">
    <div id="my_clubs">
        <h1>My Clubs</h1>
        <%= link_to "New Club", new_club_path, class: "btn btn-primary" %>
        <br><br>
        <% memberships = current_user.memberships %>
        
        <% if memberships.count == 0 %>
            <div class="jumbotron">
                <p class="lead">Looks like you aren't a member of any clubs yet.</p>
                <br>
                <p class="lead">How about starting one of your own?</p>
                <%= link_to "New Club", new_club_path, class: "btn btn-info" %>
            </div>
        <% end %>
        
        <div class="row">
            <% memberships.each do |m| %>
            <% club = current_user.clubs.find(m.club_id) %>
                <div class="col md-offset-4 col-md-4 col-md-offset-4">
                    <div class="jumbotron">
                        <h3><%= link_to club.name, club  %></h3>
                        <% if m.admin == true then %>
                            <p><strong>You are an admin</strong></p>
                        <% end %>
                        <p>Members: <%= club.memberships.count %></p>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/clubs/new.html.erb
<% @title = "New Book Club" %>
<div class="container text-center new_club">
    <h1>New Club</h1>
    <br><br>
    
    <%= form_for @club do |f| %>
        
        <h4 id="club_name">
            <%= f.label :name %> <br>
            <%= f.text_field :name %> <br>
        </h4>
        <br>
        <h4>
            <%= f.label :description %> (optional) <br>
            <%= f.text_area :description %> <br>
        </h4>
        <br>
        <p>
            <%= f.submit class: "btn btn-primary" %>
        </p>
        <p>
            <%= link_to "Cancel", root_path, style: "color: red" %>
        </p>
    <% end %>
</div>

app/views/clubs/show.html.erb
<% @title = @club.name %>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6 text-center col-md-offset-3" style="margin-top: -25px;">
            <h2><%= @club.name %></h2><br>
            <% if @club.memberships.find_by_user_id(current_user.id).admin == true then %>
                <p class="text-muted">You are an admin of this book club.</p>
                <%= button_to "Access Admin Controls", edit_club_path, 
                method: "get", class: "btn btn-primary btn-md" %>
            <% end %>
            <br>
            <% if @club.description? %>
                <div style="background: #f6f6f6">
                    <p>Description:</p>
                    <p class="text-muted small"><%= @club.description %></p>
                </div>
            <% end %>
            <br>
            <%= link_to "View Announcements", club_announcements_path(:club_id => @club.id), class: "btn btn-default" %>
        </div>
    </div>
    
    <div class="row">
        <div class="main text-center col-md-offset-3 col-md-6 col-md-offset-3">
            <% if @club.readings.count >= 1 %>
                <h1>Current Reading:</h1>
                <% c = @club.readings.where(current: true).first %>
                <% current = @club.books.find(c.book_id) %>
                <a href="/clubs/<%= @club.id%>/books/<%= current.id %>">
                    <h4><em><%= current.title %></em></h4>
                    <img src=<%=current.image %> class="img-responsive center-block book-cover">
                </a>
            <% end %>
        </div>
    </div>
    <br><br><br>
</div>

app/views/users/show.html.erb
<% @title = @user.username %>

<div class="container">
    <div class="col-md-12 text-center">
        <h1><%= @user.username %>'s Profile</h1>
        <br>
        <p class="lead"><%= @user.first_name  %> <%= @user.last_name %></p>
        <% if @user.clubs.none? %>
            <p>Does not belong to any clubs.</p>
        <% else %>
            <p class="lead">Member of:</p>
            <% @user.clubs.each do |club|%>
            <div class="col-md-4" style="background:#EBF0FA">
                
                <p class="lead"><%= link_to club.name, club_path(:id => club.id) %></p>
                
                <p>Members: <%= club.memberships.count %></p>
                
                <% if club.readings.any? %>
                    <p>Current Reading:</p>
                    <% c = club.readings.where(current: true).first %>
                    <% current = club.books.find(c.book_id) %>
                    <p class="small"><em><%= current.title %></em></p>
                    <p class="small">By: <%= current.author %></p>
                <% end %>
            </div>
            <div class="col-md-4">
                <!--space-->
            </div>
            
            <% end %>
        <% end %>
    </div>
</div>